# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('city_name', models.CharField(max_length=30)),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
