# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
    ]
