# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('isbn', models.IntegerField(max_length=14)),
                ('is_available', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
